### ISSUE TITLE
NIce

### ISSUE THREAD

**Issue by babapdtr** [s4n7h0/Script-Bucket#1]

**Comment by s4n7h0** [comment]
@babapdtr  If I understand the issue title you have given correctly, I would like to thank you for liking my work.  At the same time, I would like to write you two sentences on the usage of issue tab in GitHub. It is rather called as "bug tracker" used to create and manage bugs in the code for improved code maintenance. You could express your likes by clicking on the stars (top right hand side) or simply write an email or tweet the author of the code :) If you need more reads, visit
- https://guides.github.com/features/issues/ 
- https://help.github.com/articles/about-issues/ 

I'm closing this issue with thanks.
